// types.js
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const FETCH_TABLE_DATA_REQUEST = 'FETCH_TABLE_DATA_REQUEST';
export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const FETCH_TABLE_DATA_FAILURE = 'FETCH_TABLE_DATA_FAILURE';

export const ADD_TABLE_ITEM = 'ADD_TABLE_ITEM';
export const EDIT_TABLE_ITEM = 'EDIT_TABLE_ITEM';
export const DELETE_TABLE_ITEM = 'DELETE_TABLE_ITEM';